# Generated by Django 3.2.8 on 2021-10-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
