# Generated by Django 3.2.8 on 2021-10-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_entry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareDropTableItems',
            fields=[
                ('item', models.CharField(max_length=100)),
                ('itemAlias', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
